create table `Alquileres` (
`id_Alquiler` int not null auto_increment,
`Contrato` varchar(10),
`Vehiculo` int not null,
`Cliente` int,
`Fecha_inicio` date not null,
`Fecha_fin` date,
`km` smallint unsigned,
`Km_inicio` smallint unsigned,
`Km_fin` smallint unsigned,
`Dias` smallint unsigned,
`Precio` decimal (10,2),
`Precio km` decimal (10,2),
`Comercial` int,
`Empresa` int,
`Ciudad` varchar(15),
`Entrega` int,
`Comision_comercial` decimal(10,2),
`Ganancia` decimal(10,2),
`Observaciones` varchar(255), 
PRIMARY KEY (`id_Alquiler`),
FOREIGN KEY (`Empresa`) REFERENCES Entidad(`id_entidad`),
FOREIGN KEY (`Vehiculo`) REFERENCES Vehiculos(`id_Vehiculo`),
FOREIGN KEY (`Cliente`) REFERENCES Entidad(`id_entidad`),
FOREIGN KEY (`Comercial`) REFERENCES Comercial(`id_Comercial`)
)