create table `cuotas` (`idCuota` int AUTO_INCREMENT PRIMARY KEY,
`renting` tinyint DEFAULT NULL,
`financiado` tinyint DEFAULT NULL,
`inicio` date,
`duracion` tinyint,
`id_vehiculo` int NOT NULL,
`cuota` decimal (10,2),
`totalPagar` decimal (10,2),
`pagoFinal` decimal (10,2),
`entrada` decimal (10,2),
`fianza` decimal (10,2),
`km` int,
`kmAño`int,
`finaciera` varchar (50),
`id_entidad` int not null,
`observaciones` varchar (300),
FOREIGN KEY (`id_vehiculo`) REFERENCES vehiculos(`id_vehiculo`) ON DELETE CASCADE,
FOREIGN KEY (`id_entidad`) REFERENCES entidad (`id_entidad`) ON DELETE CASCADE);
 